### ISSUE TITLE
Linking libssh2 static library using cmake to a top level shared lib on windows

### ISSUE THREAD

**Issue by geral-victor** [libssh2/libssh2#1578]
**Describe the bug**
Cannot link libssh2 statically in a top level shared library using cmake

**To Reproduce**

``` cmake
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared libs" FORCE) # Force static build of libssh2
add_subdirectory(submodules/libssh2)

set(TARGET_SSH_TEST "ssh_test")
add_executable(TARGET_SSH_TEST src/test.cpp src/ssh.cpp)
target_include_directories(TARGET_SSH_TEST PRIVATE ./include/) 
target_link_libraries(TARGET_SSH_TEST PRIVATE libssh2) # This linking works !

add_library(${PROJECT_NAME} SHARED ${SRC_FILES})
target_link_libraries(${PROJECT_NAME} PRIVATE  libssh2) # This doesn't : MSVC throws error LNK2019 : unresolved symbols (in french: [build] ssh.obj : error LNK2019: symbole externe non r├®solu __imp_libssh2_session_init_ex r├®f├®renc├® dans la fonction "public: __cdecl Ssh::Ssh(void)" (??0Ssh@@QEAA@XZ) )
```

**Expected behavior**
Linking libssh2 statically with an executable works as intended. However, when linking it to a top level shared library, the linker is not able to use the static library : it throws error LNK2019. Why?

**Version (please complete the following information):**
 - OS and version: Windows, msvc 2022
 - libssh2 version: 1.11.1 (cloned from commit 8a871d0)
 - crypto backend and version: WinCNG

**Additional context**
See minimum reproducible example here : https://github.com/GERAL-STT/test-libssh2

**Comment by vszakats** [comment]
It looks like a `__declspec()` mismatch at first sight.

Do you mind posting the `--verbose` log to see if it reveals something?

**Comment by geral-victor** [comment]
Ok, got it: the problem comes from the fact that _WINDLL is defined (because I am building a shared library, even though I want to statically link to libssh2)

This is the relevant part of `libssh2.h` at the heart of the issue
``` C++
/* Allow alternate API prefix from CFLAGS or calling app */
#ifndef LIBSSH2_API
# ifdef _WIN32
#  if defined(LIBSSH2_EXPORTS) || defined(_WINDLL)
#   ifdef LIBSSH2_LIBRARY
#    define LIBSSH2_API __declspec(dllexport)
#   else
#    define LIBSSH2_API __declspec(dllimport)
#   endif /* LIBSSH2_LIBRARY */
#  else
#   define LIBSSH2_API
#  endif
# else /* !_WIN32 */
#  define LIBSSH2_API
# endif /* _WIN32 */
#endif /* LIBSSH2_API */
```

So a simple solution is to define `LIBSSH2_API` before including `libssh2.h`

``` C++
#define LIBSSH2_API
#include "libssh2.h"

#pragma comment(lib, "Ws2_32.lib")
```

In the end, I do think we may change this `libssh2.h` part for reflecting this scenario

**Comment by vszakats** [comment]
Do I understand correctly that your build making the DLL (what's consuming libssh2),
implicitly sets `_WINDLL`, which confuses `libssh2.h` into applying the `__declspec()`, 
while you're linking the static libssh2?

**Comment by geral-victor** [comment]
Exactly!

**Comment by vszakats** [comment]
Thanks! It explains why the same scenario works without issues with mingw-w64 (as daily tested by curl-for-win). Because mingw-w64 doesn't define `_WINDLL` on its own.

I'm not sure what's the best solution. c355d31ff94a1622526c4988b9d09074f7f7605d opted-into this behavior, which I guess makes sense for probably _most_ cases, but works against this particular one.

There is also the "classic" solution to make this choice explicit via a new `LIBSSH2_STATICLIB` macro. But it'd require everyone to set it and thus a breaking change. (It could also be added as an extra option, effectively making it a synonym to `LIBSSH2_API`.)

Your solution seems to be the most ideal, everything considered.

**Comment by geral-victor** [comment]
Thanks to you @vszakats!
In that case, for reference this is the fixed CMakeLists.txt that I use now:
``` cmake
cmake_minimum_required(VERSION 3.21.1)
project(libssh2-test VERSION 0.0.1)

set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared libs" FORCE) # Force static build of libssh2
add_subdirectory(submodules/libssh2 EXCLUDE_FROM_ALL)

add_library(${PROJECT_NAME} SHARED src/lib.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE libssh2_static Ws2_32)

# define LIBSSH2_API macro to the target (see https://github.com/libssh2/libssh2/issues/1578)
target_compile_definitions(${PROJECT_NAME} PRIVATE LIBSSH2_API=)
```

I am not an expert of cross platform compilation, but I think it is a bit frustrating that we have to defineLIBSSH2_API manually.

**Comment by vszakats** [comment]
> I am not an expert of cross platform compilation, but I think it is a bit frustrating that we have to define LIBSSH2_API manually.

Whatever solution we chose something needs to be set in certain cases.
Export/import semantics on Windows is an unfortunate design decision
made decades ago, still causing these issues all the time.

For CMake consumers, this may be an option, though I haven't tested it,
and fiddling with this is prone to unexpected side-effects:
```
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -117,7 +117,8 @@ if(BUILD_STATIC_LIBS OR BUILD_STATIC_FOR_TESTS)
   target_link_libraries(${LIB_STATIC} PRIVATE ${LIBSSH2_LIBS})
   set_target_properties(${LIB_STATIC} PROPERTIES
     PREFIX "" OUTPUT_NAME "libssh2" SOVERSION "${_libssh2_soversion}" VERSION "${_libssh2_libversion}"
-    SUFFIX "${STATIC_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}")
+    SUFFIX "${STATIC_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}"
+    INTERFACE_COMPILE_DEFINITIONS "LIBSSH2_API")
 
   target_include_directories(${LIB_STATIC}
     PRIVATE
```

**Comment by vszakats** [comment]
Made a PR out of this: #1579

It is meant to make this work without the need for a manual `#define LIBSSH2_API` workaround.
Does the patch work for you, without the workaround?

**Comment by geral-victor** [comment]
I can confirm the patch of PR https://github.com/libssh2/libssh2/pull/1579 indeed works (without the workaround).
Thank you @vszakats

**Comment by vszakats** [comment]
Thanks @geral-victor! I merged the PR.

**Comment by d3x0r** [comment]
This is still an issue... I'm not building it as an interface, but as an external project I install into a temporary path... but I'm building libssh2 as a static library, but the thing that's linking against libssh2 is a dynamic library.

``` c
|| defined(_WINDLL)  
```

That symbol really shouldn't be used in a header... just because a header is included by a file that's part of a dll, doesn't mean that libssh was compiled as a dll...   really that part should just be commented out, you already have a selection for is static/is dynamic...

**Comment by vszakats** [comment]
Since the introduction of `LIBSSH2_EXPORTS`, `_WINDLL` may be deleted
in favor that, but it will break someone's workflow.

The purpose of `_WINDLL` is foggy (possibly Microsoft's own attempt
to mitigate the disaster they created with `declspec()`?). It's also
VS-specific, and certainly not granular.

libssh2 and OpenSSL are the two outliers (that I could find) which use
this macro in their public headers. This suggest it'd better be deleted.

`_WINDLL` mentions in MS docs:
https://learn.microsoft.com/cpp/build/reference/general-property-page-project
https://learn.microsoft.com/cpp/mfc/tn011-using-mfc-as-part-of-a-dll

@d3x0r would you like to make a PR?

**Comment by d3x0r** [comment]
> 
> [@d3x0r](https://github.com/d3x0r) would you like to make a PR?

Ya I can do that.

to be technical I'm actually building with clang-cl (which is msvc emulation, but not exactly msvc).
